# Generated by Django 5.1.5 on 2025-01-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='cars/default.jpg', upload_to='cars/'),
        ),
    ]
